services:
  db:
    image: mariadb:12
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: userresu
      MARIADB_RANDOM_ROOT_PASSWORD: true
    ports:
      - 8000:8000
  app:
    build: .

volumes:
  db-data:
